dist: bionic
language: clojure
jdk:
  - openjdk8
  - openjdk11
script:
  - lein with-profile c05 test
  - lein with-profile c06 test
  - lein with-profile c07 test
  - lein with-profile c08 test
  - lein with-profile c09 test
  - lein with-profile c10 test
